spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/cocoman
    username: cocomanlocal
    password: cocomanpw
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jwt:
    secret: jwtsecretkey
cloud:
  aws:
    s3:
      bucket: cocoman-storage
    region:
      static: ap-northeast-2
    stack:
      auto: false