version: '3'
services:
  postgres:
    image: postgres:9.3
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "cocomanlocal"
      POSTGRES_PASSWORD: "cocomanpw"
      POSTGRES_DB: "cocoman"